#!/bin/sh
#
# Renders the Homebrew formula for a release to standard output.
#
#   ./homebrew_formula.sh <version> [checksums file] [bottle manifest]
#
# The formula pins the sha256 of every asset it can install, read from the
# checksums.txt built alongside them, so `brew install` verifies exactly what
# install.sh verifies.
#
# The bottle manifest is optional and has the same shape as checksums.txt, a
# hash and a bottle tag per line:
#
#   d34db33f...  arm64_ventura
#   c0ffee...    x86_64_linux
#
# Rendering without it is not a degraded mode, it is the first half of the
# release: the bottles are built by installing the formula, so the formula has
# to exist before they do. The release renders it twice — once bare to build
# against, once with the manifest to publish.
#
# The release workflow runs this and pushes the result to the tap. Nothing
# here touches the network, so it can also be run by hand against a
# downloaded checksums.txt to see what a release would publish.

set -eu

repo="yontrack/yontrack-cli"

fail() {
    printf 'error: %s\n' "$1" >&2
    exit 1
}

version=${1:-}
checksums=${2:-checksums.txt}
bottles=${3:-}

[ -n "$version" ] || fail 'usage: homebrew_formula.sh <version> [checksums file] [bottle manifest]'
[ -f "$checksums" ] || fail "$checksums does not exist, so no hash can be pinned"
[ -z "$bottles" ] || [ -f "$bottles" ] || fail "$bottles does not exist, so no bottle can be pinned"

# Reads the recorded hash for one asset, and refuses to render a formula that
# would pin something the release does not actually cover. The length check
# catches a name that matched two lines as well as a truncated file.
sha_for() {
    sha=$(awk -v name="$1" '$2 == name { print $1 }' "$checksums")
    [ -n "$sha" ] || fail "$checksums does not cover $1, so the formula cannot pin it"
    [ ${#sha} -eq 64 ] || fail "the hash $checksums records for $1 is not a sha256"
    printf '%s' "$sha"
}

# The four assets Homebrew can install, deliberately fewer than the six a
# release publishes: Homebrew supports only 64-bit Linux, so linux/386 is out,
# and there is no Homebrew on Windows at all.
#
# `|| exit 1` because fail() inside a command substitution only ends the
# subshell it runs in.
darwin_arm64=$(sha_for "yontrack-darwin-arm64") || exit 1
darwin_amd64=$(sha_for "yontrack-darwin-amd64") || exit 1
linux_arm64=$(sha_for "yontrack-linux-arm64") || exit 1
linux_amd64=$(sha_for "yontrack-linux-amd64") || exit 1

download="https://github.com/$repo/releases/download/$version"

# One `sha256` line per bottle the manifest names, in the order it names them.
# The loop reads from a redirect rather than a pipe so that it runs in this
# shell: a pipe would build the lines in a subshell and lose them.
bottle_lines=""
if [ -n "$bottles" ]; then
    while read -r sha tag || [ -n "${tag:-}" ]; do
        case "$sha" in ''|'#'*) continue ;; esac
        [ -n "$tag" ] || fail "$bottles has a hash with no bottle tag against it"
        [ ${#sha} -eq 64 ] || fail "the hash $bottles records for $tag is not a sha256"
        line="    sha256 cellar: :any_skip_relocation, $tag: \"$sha\""
        if [ -z "$bottle_lines" ]; then
            bottle_lines=$line
        else
            bottle_lines="$bottle_lines
$line"
        fi
    done < "$bottles"
fi

cat <<EOF
# Generated by homebrew_formula.sh in $repo, and pushed here by
# its release workflow. Anything edited by hand is lost at the next release;
# change the generator instead.
class Yontrack < Formula
  desc "Command line interface for Yontrack"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"
EOF

# Omitted entirely when there are no bottles: an empty `bottle do` block is a
# formula Homebrew will not load, and a tag with no tarball behind it sends it
# to a 404 rather than to the source path it would otherwise have taken.
if [ -n "$bottle_lines" ]; then
    cat <<EOF

  # Poured instead of running the install block below. Homebrew treats a
  # formula with no bottle as a source build and demands current Command Line
  # Tools for it, which is a steep toll on copying one static binary.
  #
  # The tags are older macOS versions than the runners that built them, which
  # is what makes them cover every later version: Homebrew falls back to the
  # newest bottle at or below the running system, matching on architecture.
  # Honest here only because the payload is a static binary with no SDK
  # coupling — see docs/adr/0003-homebrew-bottles.md.
  bottle do
    root_url "$download"
$bottle_lines
  end
EOF
fi

cat <<EOF

  # The released binary rather than a build from source: see
  # docs/adr/0002-homebrew-ships-the-release-binary.md in $repo.
  #
  # :nounzip stops Homebrew unpacking a bare executable, and leaves the staged
  # file named for its asset, which is what install picks up below.
  on_macos do
    on_arm do
      url "$download/yontrack-darwin-arm64", using: :nounzip
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$download/yontrack-darwin-amd64", using: :nounzip
      sha256 "$darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$download/yontrack-linux-arm64", using: :nounzip
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$download/yontrack-linux-amd64", using: :nounzip
      sha256 "$linux_amd64"
    end
  end

  def install
    # Exactly one asset is staged, under the name it carries in the release.
    bin.install Dir["yontrack-*"].first => "yontrack"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/yontrack version --cli").strip
  end
end
EOF
