#!/bin/sh
#
# Renders the Homebrew formula for a release to standard output.
#
#   ./homebrew_formula.sh <version> [checksums file]
#
# The formula pins the sha256 of every asset it can install, read from the
# checksums.txt built alongside them, so `brew install` verifies exactly what
# install.sh verifies.
#
# The release workflow runs this and pushes the result to the tap. Nothing
# here touches the network, so it can also be run by hand against a
# downloaded checksums.txt to see what a release would publish.

set -eu

repo="yontrack/yontrack-cli"

fail() {
    printf 'error: %s\n' "$1" >&2
    exit 1
}

version=${1:-}
checksums=${2:-checksums.txt}

[ -n "$version" ] || fail 'usage: homebrew_formula.sh <version> [checksums file]'
[ -f "$checksums" ] || fail "$checksums does not exist, so no hash can be pinned"

# Reads the recorded hash for one asset, and refuses to render a formula that
# would pin something the release does not actually cover. The length check
# catches a name that matched two lines as well as a truncated file.
sha_for() {
    sha=$(awk -v name="$1" '$2 == name { print $1 }' "$checksums")
    [ -n "$sha" ] || fail "$checksums does not cover $1, so the formula cannot pin it"
    [ ${#sha} -eq 64 ] || fail "the hash $checksums records for $1 is not a sha256"
    printf '%s' "$sha"
}

# The four assets Homebrew can install, deliberately fewer than the six a
# release publishes: Homebrew supports only 64-bit Linux, so linux/386 is out,
# and there is no Homebrew on Windows at all.
#
# `|| exit 1` because fail() inside a command substitution only ends the
# subshell it runs in.
darwin_arm64=$(sha_for "yontrack-darwin-arm64") || exit 1
darwin_amd64=$(sha_for "yontrack-darwin-amd64") || exit 1
linux_arm64=$(sha_for "yontrack-linux-arm64") || exit 1
linux_amd64=$(sha_for "yontrack-linux-amd64") || exit 1

download="https://github.com/$repo/releases/download/$version"

cat <<EOF
# Generated by homebrew_formula.sh in $repo, and pushed here by
# its release workflow. Anything edited by hand is lost at the next release;
# change the generator instead.
class Yontrack < Formula
  desc "Command line interface for Yontrack"
  homepage "https://github.com/$repo"
  version "$version"
  license "MIT"

  # The released binary rather than a build from source: see
  # docs/adr/0002-homebrew-ships-the-release-binary.md in $repo.
  #
  # :nounzip stops Homebrew unpacking a bare executable, and leaves the staged
  # file named for its asset, which is what install picks up below.
  on_macos do
    on_arm do
      url "$download/yontrack-darwin-arm64", using: :nounzip
      sha256 "$darwin_arm64"
    end
    on_intel do
      url "$download/yontrack-darwin-amd64", using: :nounzip
      sha256 "$darwin_amd64"
    end
  end

  on_linux do
    on_arm do
      url "$download/yontrack-linux-arm64", using: :nounzip
      sha256 "$linux_arm64"
    end
    on_intel do
      url "$download/yontrack-linux-amd64", using: :nounzip
      sha256 "$linux_amd64"
    end
  end

  def install
    # Exactly one asset is staged, under the name it carries in the release.
    bin.install Dir["yontrack-*"].first => "yontrack"
  end

  test do
    assert_equal version.to_s, shell_output("#{bin}/yontrack version --cli").strip
  end
end
EOF
